version: '3.8'

services:
  boku-ai:
    build: .
    ports:
      - "7871:7871"
    environment:
      - HF_API_KEY=${HF_API_KEY}
      - SERVER_PORT=7871
      - SERVER_HOST=0.0.0.0
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:7871/health', timeout=10)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
